replicaCount: 1

image:
  repository: your-registry/account-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: account.yourdomain.com
  ingressClass: traefik
