replicaCount: 1

image:
  repository: https://github.com/davidnet-net/account
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: account.davidnet.net
  ingressClass: traefik
